<a href="https://colab.research.google.com/github/vamsi160505-design/MLDA/blob/main/T10_Hierarchical_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# (i)Classificaton - confusion matrix
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.cluster import AgglomerativeClustering
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
iris = load_iris()
x = iris.data[:, :2]
y = iris.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,
random_state=42)
hc_model = AgglomerativeClustering(n_clusters=3, linkage='ward')
y_hc = hc_model.fit_predict(x_test)
print("Classification Report:\n", classification_report(y_test, y_hc))
cm = confusion_matrix(y_test, y_hc)
print("Confusion Matrix:\n", cm)

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.00      0.00      0.00         9
           2       0.12      0.09      0.11        11

    accuracy                           0.03        30
   macro avg       0.04      0.03      0.04        30
weighted avg       0.05      0.03      0.04        30

Confusion Matrix:
 [[ 0 10  0]
 [ 2  0  7]
 [10  0  1]]
