<a href="https://colab.research.google.com/github/vamsi160505-design/MLDA/blob/main/T8_Naive_Bayes_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report
iris = load_iris()
y = iris.target
x = iris.data[:, :2]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,
random_state=21)
model = GaussianNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print("Classification Report:\n", classification_report(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.69      0.75      0.72        12
           2       0.50      0.43      0.46         7

    accuracy                           0.77        30
   macro avg       0.73      0.73      0.73        30
weighted avg       0.76      0.77      0.76        30

Confusion Matrix:
 [[11  0  0]
 [ 0  9  3]
 [ 0  4  3]]
