<a href="https://colab.research.google.com/github/vamsi160505-design/MLDA/blob/main/T9_Support_Vector_Machinesb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
iris = datasets.load_iris()
x = iris.data[:, :2]
y = iris.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,
random_state=21)
model = SVC(kernel='linear')
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print("Classification Report:\n", classification_report(y_test,
y_pred))
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.73      0.67      0.70        12
           2       0.50      0.57      0.53         7

    accuracy                           0.77        30
   macro avg       0.74      0.75      0.74        30
weighted avg       0.77      0.77      0.77        30

Confusion Matrix:
 [[11  0  0]
 [ 0  8  4]
 [ 0  3  4]]
